name: Test Every Chapter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install essential lib
      run: |
        wget -q https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
        unzip -q libtorch-shared-with-deps-latest.zip
        ls
  

  build1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install essential lib
      run: |
        ls

  build3:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install essential lib
      run: |
        ls
